config/routes.rb
Rails.application.routes.draw do

  root "staticpages#top"

  resources :users, only: [:new, :create]
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :answers, only: [:index, :show, :new ,:create]
  resources :questions, only: [:index, :show, :new ,:create]
  
end

app/models/answer.rb
class Answer < ApplicationRecord  
  belongs_to :question
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
    has_many :answers, dependent: :destroy

    #ユーザーが解答した質問だけ表示するようにする
    def self.display_questions(id)
        # ログインユーザーのIDを取得
        last_answer = Answer.where(user_id: id).order(created_at: :desc).first # 最後に解答した問題を取得
      
        if last_answer
          # 最後に解答した問題の次の問題を取得
          question = Question.where('id > ?', last_answer.question_id).first
        else
          # 新規登録時は1問目を出力
          question = Question.first
        end
    end

    def self.answered_question(user_id)
      Question.joins(:answers).where(answers: { user_id: user_id })
    end

end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: { minimum: 5 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :name, presence: true, length: { maximum: 255 }
  validates :email, presence: true, uniqueness: true

  has_many :answers

  def last_answer
    last_answer = self.answers.order(created_at: :desc).first
  end

  def last_answered_question
    last_answer = self.answers.order(created_at: :desc).first
    if last_answer
      Question.where('id > ?', last_answer.question_id).first
    else
      Question.first
    end
  end

  def passed_24_hours?
    #回答したかつ、24時間継続している場合
    last_answer = self.answers.order(created_at: :desc).first
    if last_answer && last_answer.created_at < 24.hours.ago
      return true
    end
    #初期登録時
    if last_answer == nil
      return true
    end
      return false
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :require_login
  before_action :is_answered?, only: [:show]

  def index
    @answers = current_user.answers.includes(:question)
  end

  def show
    @answer = Answer.find_by(id: params[:id])
  end

  def new;end

  def create
    @answer = Answer.new(answer_params)
    @answer.user_id = current_user.id
    if @answer.save
      redirect_to answers_path, notice: t('answers.create.success')
    else
      flash.now[:warning] = t('answers.create.failure')
      render 'questions/new',  status: :unprocessable_entity
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:content, :question_id)
  end

  def is_answered?
    return redirect_to answers_path unless @answer = Answer.find_by(id: params[:id])
    return redirect_to answers_path unless @answer && Answer.find_by(question_id: @answer.question_id, user_id: current_user.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :require_login
  before_action :is_answered?, only: [:show]
  def index
    @questions = Question.answered_question(current_user.id)
  end

  def show
    @question = Question.find_by(id:  params[:id])
    @answers = @question.answers
  end
    
  def new
    @question = current_user.last_answered_question
    @answer = Answer.new
    @last_answer = current_user.last_answer
    @passed_24_hours = current_user.passed_24_hours?
  end

  private

  def is_answered?
    answer = Answer.find_by(question_id: params[:id], user_id: current_user.id)
    redirect_to answers_path unless answer
  end
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def top
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = login(params[:email],params[:password])
    if @user
      redirect_to new_question_path, notice: t('user_sessions.create.success')
    else
      flash.now[:warning] = t('user_sessions.create.failure')
      render :new,  status: :unprocessable_entity
    end
  end

  def destroy
    logout
    redirect_to root_path, status: :see_other, notice: t('user_sessions.destroy.success')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    
    @user = User.new(user_params)
    if @user.save
      login(params[:user][:email],params[:user][:password])
      redirect_to new_question_path, notice: t('users.create.success')   
    else
      flash.now[:warning] = t('users.create.failure')
      render :new,  status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Answers#create</h1>
  <p>Find me in app/views/answers/create.html.erb</p>
</div>

app/views/answers/index.html.erb
<div class="flex flex-col items-center mt-5">
  <% @answers.each do |answer|%>
    <h1 class="mt-3 text-2xl font-bold btn glass"><%= link_to answer.question.title, question_path(answer.question.id)%></h1>
  <% end %>
</div>

app/views/answers/new.html.erb
<div>
  <h1 class="font-bold text-4xl">Answers#new</h1>
  <p>Find me in app/views/answers/new.html.erb</p>
</div>

app/views/answers/show.html.erb
<div class="hero min-h-screen bg-base-200">
  <div class="hero-content flex-col lg:flex-row-reverse">
    <div class="text-center lg:text-left mr-10">
      <h1 class="text-5xl font-bold ml-5"><%= @answer.question.title%></h1>
      <h1 class="text-2xl font-bold mt-2 ml-5">とは何？</h1>
    </div>
    <div class="card flex-shrink-0 w-full max-w-md shadow-2xl bg-base-100">
      <div class="card-body">
        <div class="form-control">
            <%= @answer.user.name %>
        </div>
        <%= text_area_tag :answer_content, @answer.content, class: "form-control", rows: 4 %>
      </div>
    </div>
    </div>
  </div>
</div>

app/views/layouts/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type == 'notice'%>
  <div class="alert alert-success">
    <svg xmlns="http://www.w3.org/2000/svg" class="font-bold stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
    <span><%= message %></span>
  </div>
  <% else %>
  <div class="alert alert-warning">
    <svg xmlns="http://www.w3.org/2000/svg" class="font-bold stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
    <span><%= message %></span>
  </div>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class=" fixed bottom-0 footer footer-center p-4 bg-base-300 text-base-content">
  <div>
    <p>Copyright © 2023 - All right reserved by 1Day Web Quiz</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar bg-base-100">
  <div class="navbar-start">
    <a class="btn btn-ghost normal-case text-xl">1day Web Quiz</a>
  </div>
  <% if logged_in? %>
    <div class="navbar-center">
      <%= link_to '一覧', answers_path, class: "btn btn-ghost normal-case text-xl" %>
      <%= link_to '回答する', new_question_path, class: "btn btn-ghost normal-case text-xl" %>
    </div>
  <% end %>
  <div class="navbar-end">
    <% if logged_in? %>
      <%= link_to 'Log out', logout_path, data: { turbo_method: :delete}, class: "btn" %>
    <% else %>
      <%= link_to 'Sign up', new_user_path, class: "btn" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>1day Web Quiz</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <%= render 'layouts/header' %>
      <%= render 'layouts/flash_message' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
  </body>
</html>

app/views/questions/new.html.erb
<% if @passed_24_hours %>
<div class="hero min-h-screen bg-base-200">
  <div class="hero-content flex-col lg:flex-row-reverse">
    <div class="text-center lg:text-left mr-10">
      <h1 class="text-5xl font-bold ml-5"><%= @question.title%></h1>
      <h1 class="text-2xl font-bold mt-2 ml-5">とは何？</h1>
    </div>
    <%= form_with model: @answer, class: "card flex-shrink-0 w-full max-w-md shadow-2xl bg-base-100" do |form| %>
        <div class="card-body">
          <div class="form-control">
            <%= form.text_area :content, placeholder: "出来るだけ自分の言葉で説明してください", class: "focus:ring focus:ring-white border border-white", style: "height: 200px;" %>
          </div>
            <%= form.hidden_field :question_id, value: @question.id%>
          <div class="form-control mt-6">
            <%= form.submit "回答する", type: "submit", class: "btn btn-primary rounded hover:bg-gray-500 hover:border-gray-500" %>
          </div>
        </div>
    <% end %>
    </div>
  </div>
</div>
<% else %>
<div class="hero min-h-screen bg-base-200">
  <div class="hero-content flex-col lg:flex-row-reverse">
    <div class="text-center lg:text-left mr-10">
      <% if @last_answer%>
        <h1 class="text-2xl font-bold mt-2 ml-5 mb-1">次の回答は</h1>
        <h1 class="text-5xl font-bold ml-5"><%= (@last_answer.created_at + 1.days).to_s(:datetime_jp) %></h1>
        <h1 class="text-2xl font-bold mt-2 ml-5">までお待ちください</h1>
      <% end %>
    </div>
    </div>
  </div>
</div>
<% end %>

app/views/questions/show.html.erb
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-col text-center w-full mb-20">
      <h2 class="text-xs text-gray-500 tracking-widest font-medium title-font mb-1">1Day Quiz</h2>
      <h1 class="sm:text-3xl text-2xl font-bold title-font mb-4 text-gray-900"><%= @question.title%></h1>
    </div>
    <div class="flex flex-wrap">
      <% @answers.each do |answer|%>
      <div class="xl:w-1/4 lg:w-1/2 md:w-full px-8 py-6 border-l-2 border-gray-200 border-opacity-60">
        <h2 class="text-lg sm:text-xl text-gray-900 font-bold title-font mb-2"><%= answer.user.name %>さん</h2>
        <p class="leading-relaxed text-base mb-4"><%= truncate(answer.content, length: 30) %></p>
        <%= link_to answer_path(answer), class: "text-gray-500 inline-flex items-center" do %>さらに読む
          <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
            <path d="M5 12h14M12 5l7 7-7 7"></path>
          </svg>
        <% end %>
      </div>
      <% end %>
    </div> 
  </div>
</section>

app/views/staticpages/top.html.erb
<div class="hero min-h-screen bg-base-200">
  <div class="hero-content text-center">
    <div class="max-w-md">
      <h1 class="text-5xl font-bold">1日1個のクイズだけ</h1>
      <p class="py-6 font-bold">1日1問しか解けない記述式のクイズで、言語化力を高めよう。解答しないと他の回答者の答えも見れないよ！</p>
      <%= link_to 'Get Started', login_path, class: "btn btn-primary"%>
    </div>
  </div>
</div>

app/views/user_sessions/create.html.erb
<div>
  <h1 class="font-bold text-4xl">UserSessions#create</h1>
  <p>Find me in app/views/user_sessions/create.html.erb</p>
</div>

app/views/user_sessions/destroy.html.erb
<div>
  <h1 class="font-bold text-4xl">UserSessions#destroy</h1>
  <p>Find me in app/views/user_sessions/destroy.html.erb</p>
</div>

app/views/user_sessions/new.html.erb
<div class="flex items-center min-h-screen bg-white dark:bg-gray-900">
    <div class="container mx-auto">
        <div class="max-w-md mx-auto my-2">
            <div class="text-center">
                <h1 class="my-3 text-3xl font-semibold text-gray-700 dark:text-gray-200">Log in</h1>
            </div>
            <div class="m-7">
            <%= form_with url: login_path, class: "mb-6" do |form| %>
              <div class="mb-6">
                <%= form.label :email,  class: "block mb-2 text-sm text-gray-600 dark:text-gray-400" %>
                <%= form.email_field :email, placeholder: "you@example.com", class: "w-full px-3 py-2 placeholder-gray-300 border border-gray-300 rounded-md focus:outline-none focus:ring focus:ring-indigo-100 focus:border-indigo-300 dark:bg-gray-700 dark:text-white dark:placeholder-gray-500 dark:border-gray-600 dark:focus:ring-gray-900 dark:focus:border-gray-500" %>
              </div>
              <div class="mb-6">
                <div class="flex justify-between mb-2">
                <%= form.label :password,  class: "text-sm text-gray-600 dark:text-gray-400" %>
                </div>
                <%= form.password_field :password, placeholder: "Your Password", class: "w-full px-3 py-2 placeholder-gray-300 border border-gray-300 rounded-md focus:outline-none focus:ring focus:ring-indigo-100 focus:border-indigo-300 dark:bg-gray-700 dark:text-white dark:placeholder-gray-500 dark:border-gray-600 dark:focus:ring-gray-900 dark:focus:border-gray-500" %>
              </div>
              <div class="mb-6">
                <%= form.button "ログインする", type: "submit", class: "w-full px-3 py-4 text-white bg-gray-400 rounded-md focus:outline-none font-bold" %>
              </div>
              <p class="text-sm text-center text-gray-400">
                新規登録はお済みですか？ <%= link_to t('.to_register_page'), new_user_path, class: "text-red-300 focus:outline-none focus:underline focus:text-gray-500 dark:focus:border-gray-800" %>
            <% end %>
            </div>
        </div>
    </div>
</div>

app/views/users/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Users#create</h1>
  <p>Find me in app/views/users/create.html.erb</p>
</div>

app/views/users/new.html.erb
<div class="flex items-center min-h-screen bg-white dark:bg-gray-900">
    <div class="container mx-auto">
        <div class="max-w-md mx-auto my-2">
            <div class="text-center">
                <h1 class="my-3 text-3xl font-semibold text-gray-700 dark:text-gray-200">Sign Up</h1>
            </div>
            <div class="m-7">
            <%= form_with model: @user, class: "mb-6" do |form| %>
              <div class="mb-6">
                <div class="flex justify-between mb-2">
                <%= form.label :name, class: "text-sm text-gray-600 dark:text-gray-400" %>
                </div>
                <%= form.text_field :name, placeholder: "Web太郎", class: "w-full px-3 py-2 placeholder-gray-300 border border-gray-300 rounded-md focus:outline-none focus:ring focus:ring-indigo-100 focus:border-indigo-300 dark:bg-gray-700 dark:text-white dark:placeholder-gray-500 dark:border-gray-600 dark:focus:ring-gray-900 dark:focus:border-gray-500" %>
              </div>
              <div class="mb-6">
                <%= form.label :email,  class: "block mb-2 text-sm text-gray-600 dark:text-gray-400" %>
                <%= form.email_field :email, placeholder: "example@example.com", class: "w-full px-3 py-2 placeholder-gray-300 border border-gray-300 rounded-md focus:outline-none focus:ring focus:ring-indigo-100 focus:border-indigo-300 dark:bg-gray-700 dark:text-white dark:placeholder-gray-500 dark:border-gray-600 dark:focus:ring-gray-900 dark:focus:border-gray-500" %>
              </div>
              <div class="mb-6">
                <div class="flex justify-between mb-2">
                <%= form.label :password,  class: "text-sm text-gray-600 dark:text-gray-400" %>
                </div>
                <%= form.password_field :password, placeholder: "6文字以上で設定してください", class: "w-full px-3 py-2 placeholder-gray-300 border border-gray-300 rounded-md focus:outline-none focus:ring focus:ring-indigo-100 focus:border-indigo-300 dark:bg-gray-700 dark:text-white dark:placeholder-gray-500 dark:border-gray-600 dark:focus:ring-gray-900 dark:focus:border-gray-500" %>
              </div>
              <div class="mb-6">
                <div class="flex justify-between mb-2">
                <%= form.label :password_confirmation, class: "text-sm text-gray-600 dark:text-gray-400" %>
                </div>
                <%= form.password_field :password_confirmation, placeholder: "もう一度入力してください", class: "w-full px-3 py-2 placeholder-gray-300 border border-gray-300 rounded-md focus:outline-none focus:ring focus:ring-indigo-100 focus:border-indigo-300 dark:bg-gray-700 dark:text-white dark:placeholder-gray-500 dark:border-gray-600 dark:focus:ring-gray-900 dark:focus:border-gray-500" %>
              </div>
              <div class="mb-6">
                <%= form.button "登録する", type: "submit", class: "w-full px-3 py-4 text-white bg-gray-400 rounded-md focus:outline-none font-bold" %>
              </div>
              <p class="text-sm text-center text-gray-400">
                新規登録はお済みですか？ <%= link_to t('.to_login_page'),login_path, class: "text-red-300 focus:outline-none focus:underline focus:text-gray-500 dark:focus:border-gray-500" %>
              </p>
            <% end %>
            </div>
        </div>
    </div>
</div>